language: swift

osx_image: xcode12


env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=14.0 NAME='iPhone 11'
    - TEST_SDK=iphonesimulator12.1 OS=13.1 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project QuiteAdaptableKit.xcodeproj -scheme QuiteAdaptableKit -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
